# app setup
application: YOUR_APP_ID
version: dev
runtime: python27
api_version: 1
threadsafe: true

# cache expires
default_expiration: "30d"

# ignores
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^LICENSE
- ^README\..*
- \.gitignore
- ^\.git/.*

# builtins
builtins:
- appstats: on #/_ah/stats/
- remote_api: on #/_ah/remote_api/

# statics
- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: site/static/favicon.ico
  upload: site/static/favicon.ico

- url: /(robots\.txt|crossdomain\.xml)
  static_files: site/static/\1
  upload: site/static/(robots\.txt|crossdomain\.xml)

- url: /css
  mime_type: text/css
  static_dir: site/static/css

- url: /js
  mime_type: text/javascript
  static_dir: site/static/js

- url: /img/(.*\.(gif|png|jpg))
  static_files: site/static/img/\1
  upload: site/static/img/(.*\.(gif|png|jpg))

- url: /.*
  script: main.app

# secure mode
secure: always

# libraries
libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: markupsafe
  version: "0.15"
- name: pycrypto
  version: "2.6"

error_handlers:
  - error_code: over_quota
    file: site/templates/errors/over_quota.html

  - error_code: dos_api_denial
    file: site/templates/errors/dos_api_denial.html

  - error_code: timeout
    file: site/templates/errors/timeout.html

